version: '2'
services:
    mongodb:
        image: mongo:3.6.3
        container_name: "some-mongo"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - /home/mongo/Databases/MongoDB:/data/db
        ports:
            - 27017:27017
        command: mongod # --quiet`